export const KOYLA_GET_WORDS_BEGIN = 'KOYLA_GET_WORDS_BEGIN';
export const KOYLA_GET_WORDS_SUCCESS = 'KOYLA_GET_WORDS_SUCCESS';
export const KOYLA_GET_WORDS_FAILURE = 'KOYLA_GET_WORDS_FAILURE';
export const KOYLA_GET_WORDS_DISMISS_ERROR = 'KOYLA_GET_WORDS_DISMISS_ERROR';
export const KOYLA_ON_INPUT_CHANGE = 'KOYLA_ON_INPUT_CHANGE';
